package defencesystem;

public class HelicopterWindow extends javax.swing.JFrame implements DefenceObserver {

    private int position;

    /**
     * Creates new form HelicopterWindow
     */
    public HelicopterWindow() {
        initComponents();
        setTitle("Helicopter");
        setSize(798, 600);
        setLocationRelativeTo(this);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnMissileOperation = new javax.swing.JButton();
        btnLaserOperation = new javax.swing.JButton();
        positionCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        msgTextField = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblArea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("Area Not Cleared");
        getContentPane().add(lblArea);
        lblArea.setBounds(60, 60, 210, 37);

        btnShoot.setBackground(new java.awt.Color(0, 255, 255));
        btnShoot.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnShoot.setText("Shoot");
        btnShoot.setEnabled(false);
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });
        getContentPane().add(btnShoot);
        btnShoot.setBounds(60, 130, 162, 35);

        btnMissileOperation.setBackground(new java.awt.Color(0, 255, 255));
        btnMissileOperation.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMissileOperation.setText("Missile Operation");
        btnMissileOperation.setEnabled(false);
        btnMissileOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileOperationActionPerformed(evt);
            }
        });
        getContentPane().add(btnMissileOperation);
        btnMissileOperation.setBounds(240, 130, 164, 35);

        btnLaserOperation.setBackground(new java.awt.Color(0, 255, 255));
        btnLaserOperation.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLaserOperation.setText("Laser Operation");
        btnLaserOperation.setEnabled(false);
        btnLaserOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaserOperationActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaserOperation);
        btnLaserOperation.setBounds(60, 180, 162, 35);

        positionCheckBox.setBackground(new java.awt.Color(11, 26, 46));
        positionCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        positionCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        positionCheckBox.setText("Position");
        positionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(positionCheckBox);
        positionCheckBox.setBounds(550, 80, 124, 38);

        msgTextArea.setColumns(20);
        msgTextArea.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        msgTextArea.setRows(5);
        msgTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        msgTextArea.setEnabled(false);
        jScrollPane1.setViewportView(msgTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 240, 537, 204);

        msgTextField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        msgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(msgTextField);
        msgTextField.setBounds(60, 460, 420, 38);

        btnSend.setBackground(new java.awt.Color(255, 255, 51));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend);
        btnSend.setBounds(500, 460, 99, 38);

        jLabel1.setBackground(new java.awt.Color(11, 26, 46));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defencesystem/resized_frame_780x650.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 790, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShootActionPerformed

    private void msgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgTextFieldActionPerformed

    private void positionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionCheckBoxActionPerformed

    private void btnLaserOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaserOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaserOperationActionPerformed

    private void btnMissileOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMissileOperationActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String msg = "Helicopter : " + msgTextField.getText();
        MainController.setDefenceMsg(msg);
        try {
            javax.swing.text.Document doc = msgTextArea.getDocument();
            doc.insertString(doc.getLength(), "You: " + msgTextField.getText() + "\n", null);
            msgTextArea.setCaretPosition(doc.getLength());
        } catch (javax.swing.text.BadLocationException e) {

        }
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelicopterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelicopterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelicopterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelicopterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnLaserOperation;
    public static javax.swing.JButton btnMissileOperation;
    private javax.swing.JButton btnSend;
    public static javax.swing.JButton btnShoot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblArea;
    private javax.swing.JTextArea msgTextArea;
    private javax.swing.JTextField msgTextField;
    private static javax.swing.JCheckBox positionCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int position) {
        this.position = position;
        updateButtons();
    }

    @Override
    public void getMsgMain(String msg) {
        try {
            javax.swing.text.Document doc = msgTextArea.getDocument();
            doc.insertString(doc.getLength(), "Maincontroller: " + msg + "\n", null);
            msgTextArea.setCaretPosition(doc.getLength());

        } catch (javax.swing.text.BadLocationException e) {

        }
    }

    @Override
    public void areaClearLabel(boolean clearStatus) {
        if (clearStatus) {
            lblArea.setText("Area Cleared");
        } else {
            lblArea.setText("Area Not Cleared");
        }
    }

    @Override
    public void updateButtons() {
        if (positionCheckBox.isSelected()) {
            if (position > 60) {
                btnLaserOperation.setEnabled(true);
                btnMissileOperation.setEnabled(true);
                btnShoot.setEnabled(true);
            } else if (position > 40) {
                btnMissileOperation.setEnabled(true);
                btnShoot.setEnabled(true);
            } else if (position > 20) {
                btnShoot.setEnabled(true);
            }

            if (position < 20) {
                btnLaserOperation.setEnabled(false);
                btnMissileOperation.setEnabled(false);
                btnShoot.setEnabled(false);
            } else if (position < 40) {
                btnLaserOperation.setEnabled(false);
                btnMissileOperation.setEnabled(false);
            } else if (position < 60) {
                btnLaserOperation.setEnabled(false);
            }
        }
    }

}
