package defencesystem;

public class MainController extends javax.swing.JFrame {

    private final DefenceObserverableInterface defenceObserverableInterface;

    /**
     * Creates new form MainController
     *
     * @param defenceObserverableInterface
     */
    public MainController(DefenceObserverableInterface defenceObserverableInterface) {
        initComponents();
        this.defenceObserverableInterface = defenceObserverableInterface;
        setTitle("Main Controller");
        setSize(798, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jSlider1 = new javax.swing.JSlider();
        jSpinner1 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        sliderPosition = new javax.swing.JSlider();
        btnSend = new javax.swing.JButton();
        lblW = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AreaCheckBox = new javax.swing.JCheckBox();
        messageTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        sliderPosition.setBackground(new java.awt.Color(0, 255, 255));
        sliderPosition.setMajorTickSpacing(20);
        sliderPosition.setMinorTickSpacing(10);
        sliderPosition.setPaintLabels(true);
        sliderPosition.setPaintTicks(true);
        sliderPosition.setSnapToTicks(true);
        sliderPosition.setValue(0);
        sliderPosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPositionStateChanged(evt);
            }
        });
        jPanel1.add(sliderPosition);
        sliderPosition.setBounds(70, 430, 320, 59);

        btnSend.setBackground(new java.awt.Color(255, 255, 51));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend);
        btnSend.setBounds(570, 256, 106, 34);

        lblW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(lblW);
        lblW.setBounds(291, 490, 235, 56);

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("DEFENSE SYSYTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 60, 410, 70);

        AreaCheckBox.setBackground(new java.awt.Color(11, 26, 46));
        AreaCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AreaCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        AreaCheckBox.setText("Area Clear");
        AreaCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AreaCheckBoxItemStateChanged(evt);
            }
        });
        AreaCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AreaCheckBoxStateChanged(evt);
            }
        });
        AreaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(AreaCheckBox);
        AreaCheckBox.setBounds(570, 70, 136, 37);

        messageTextField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(messageTextField);
        messageTextField.setBounds(519, 173, 211, 65);

        messageTextArea.setColumns(20);
        messageTextArea.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        messageTextArea.setRows(5);
        messageTextArea.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 150, 255)));
        messageTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        messageTextArea.setEnabled(false);
        jScrollPane1.setViewportView(messageTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 150, 401, 248);

        jLabel1.setBackground(new java.awt.Color(11, 26, 46));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defencesystem/resized_frame_780x650.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 790, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderPositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPositionStateChanged
        int position = sliderPosition.getValue();
        defenceObserverableInterface.setPosition(position);
    }//GEN-LAST:event_sliderPositionStateChanged

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        defenceObserverableInterface.getMsgMain(messageTextField.getText());
        try {
            javax.swing.text.Document doc = messageTextArea.getDocument();
            doc.insertString(doc.getLength(), "You: " + messageTextField.getText() + "\n", null);
            messageTextArea.setCaretPosition(doc.getLength());
        } catch (javax.swing.text.BadLocationException e) {

        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void AreaCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AreaCheckBoxItemStateChanged

    }//GEN-LAST:event_AreaCheckBoxItemStateChanged

    private void AreaCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AreaCheckBoxStateChanged

    }//GEN-LAST:event_AreaCheckBoxStateChanged

    private void AreaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaCheckBoxActionPerformed
        defenceObserverableInterface.areaClear(AreaCheckBox.isSelected());
    }//GEN-LAST:event_AreaCheckBoxActionPerformed

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    public void updateInbox() {
        messageTextArea.setText("");
    }

    public static void setDefenceMsg(String msg) {
        try {
            javax.swing.text.Document doc = messageTextArea.getDocument();
            doc.insertString(doc.getLength(), msg + "\n", null);
            messageTextArea.setCaretPosition(doc.getLength());
        } catch (javax.swing.text.BadLocationException e) {

        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox AreaCheckBox;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblW;
    public static javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JSlider sliderPosition;
    // End of variables declaration//GEN-END:variables
}
